[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[invariant]
runs = 128
depth = 8
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
