name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quick-checks-unit-tests:
    name: Forge unit tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2

      - name: Install JavaScript dependencies
        run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run solhint lint check
        run: npm run lint:check
      
      - name: Install submodules
        run: forge install

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run tests
        run: forge test --optimize

      - name: Coverage
        run: |
          forge coverage --report lcov
        id: coverage

      - uses: codecov/codecov-action@v3

  # static-analysis:
  #   name: Slither static analysis
  #   runs-on: ubuntu-latest
  #   steps:

  #     - uses: actions/checkout@v3

  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly
      
  #     - name: Install submodules
  #       run: forge install

  #     - name: Run Slither
  #       uses: crytic/slither-action@v0.2.0
  #       with:
  #         target: "src/"
  #         slither-config: slither.config.json
  #         sarif: results.sarif
  #         fail-on: high
